version: '3.8'

services:

  db:
    container_name: libreria
    image: mongo:6.0
    volumes:
      - libreria-vol:/data/db
    ports:
      - 27017:27017  # no exponemos el puerto de nuestra bd, si los unicos que utilizaran nuestra bd son los contenedores que están en estre docker-compose
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: salvador
      MONGO_INITDB_ROOT_PASSWORD: 123456
    command: [ '--auth' ] # hace obligatorio utilizar contraseñas para ingresar al contendor.

  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: salvador
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: libreria
    ports:
      - 8081:8081
    restart: always

  backend:
    image: humbertoto22/libreria_futuro:latest
    container_name: backend
    ports:
      - "8080:8080"  # Expone el puerto 8080 para acceder a la aplicación
    environment:
      MONGODB: salvador:123456@libreria:27017
    depends_on:
      - db
      - mongo-express
    restart: always

volumes:
  libreria-vol:
    external: false


