server:
  port: 8080
spring:
  application:
    name: "libreria"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/libreria_bd
    username: postgres
    password: Humberto22092

# Se debe buscar la forma de que cuando el proyecto se levante cree las tablas de la BD automáticamente.
# Ya sea mediante un archivo SQL o cualquier otro método.


rabbitmq:
  port: 5672
  host: localhost
  username: guest
  password: guest
  virtualHost: myVHost
  concurrentConsumers: 5
