server:
  port: 8080
spring:
  application:
    name: "libreria"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/libreria_bd
    username: postgres
    password: Humberto22092

  data:
    mongodb:
      uri: mongodb://localhost:27017/libreria_db

# debería la url estar de la siguiente manera ya que cuando se cree el contenedor apunte a la BD y no al mismo contenedor por el localhost
# url: r2dbc:postgresql://postgres-db:5432/libreria_bd

rabbitmq:
  port: 5672
  host: localhost
  username: guest
  password: guest
  virtualHost: myVHost
  concurrentConsumers: 5

aws:
  s3:
    bucket: nombre-del-bucket
    region: us-east-1
    access-key: TU_ACCESS_KEY
    secret-key: TU_SECRET_KEY

