server:
  port: 8080
spring:
  application:
    name: "libreria"

  profiles:
    active: ${APP_PROFILE:local} # Perfil por defecto: local

  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/libreria_bd
    username: postgres
    password: Humberto22092

  data:
    mongodb:
      uri: mongodb://${MONGODB}
      database: libreria_db
      #uri: mongodb://localhost:27017/libreria_db

rabbitmq:
  port: 5672
  host: localhost
  username: guest
  password: guest
  virtualHost: myVHost
  concurrentConsumers: 5

aws:
  s3:
    bucket: nombre-del-bucket
    region: us-east-1
    access-key: TU_ACCESS_KEY
    secret-key: TU_SECRET_KEY

logging:
  level:
    root: DEBUG

---
spring:
  config.activate.on-profile: kubernetes

  data:
    mongodb:
      uri: mongodb://${MONGO_URI}
      database: libreria_db
      #uri: mongodb://${DB_USER}:${DB_PASSWORD}@${MONGO_HOST:mongo-service}:${MONGO_PORT:27017}/${DB_NAME:libreria_db}?authMechanism=SCRAM-SHA-256

#rabbitmq:
#  host: rabbitmq-service