# SECRET archivo donde están encriptadas las credenciales de Mongo express.
apiVersion: v1
kind: Secret # tipo de archivo.
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_HOST: "mongo-service"  # "mongo-service" en base64, este es el servico de la Base de datos.
  MONGO_PORT: "27017"            # "27017" en base64
  MONGO_DB: "libreria_db"       # "libreria_db" en base64
  MONGO_URI: "mongo-service:27017/libreria_db"
# MONGDDB => mongo-service:27017/libreria_db  

# NOTA: Las claves en Secret de Kubernetes deben ir codificadas en base64 solo cuando usas la propiedad data, no cuando utilizas stringData.